# Antora Playbook for building the documentation site
# This playbook is used for local development and CI builds

site:
  title: Antora Dark Theme
  url: https://the-dev-center.github.io/antora-dark-theme
  start_page: antora-dark-theme:guide:index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./build/site

asciidoc:
  attributes:
    source-highlighter: highlight.js
    icons: font
